---
- name: Install backends
  hosts:
    - backend1
    - backend2
  tasks:
    - name: Install Apache
      become: yes
      apt:
        update_cache: yes
        pkg:
          - apache2
    - name: Replace the index file
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
      become: yes
